include device/google/cuttlefish/vsoc_x86/BoardConfig.mk

#BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
TARGET_FS_CONFIG_GEN += device/sandy/${TARGET_PRODUCT}/config.fs
#ALLOW_MISSING_DEPENDENCIES=true
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
#TARGET_SUPPORTS_64_BIT_APPS := false
#BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
#BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true
#BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
#BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true

